# Use the new container-based infrastructure
sudo: false

# Install some apt packages needed for spcomp
addons:
    apt:
        sources: 
            - deadsnakes
        packages:
            - lib32stdc++6
            # We need at least python3.4 to run our custom deployment scripts
            - python3.5

# Set the build environment
env:
    global:
        - PROJECT_SHORTNAME="example"
        - UPDATER_REPO="sm_updater"
        - UPDATER_USER="servadestroya"
        - URL="https://github.com/$UPDATER_USER/sample_plugin_autoupdated"
        #UPDATER_REPO_OAUTH
        - secure: "uALRIL2YpLP9h8vTPY2Bk9ZyS9iOYUOBkpmYUKCJeXg0zgcAwhCJ1KJFccnUN9dD6d1uQhspw/6Y0+g7S0FAku1DkXueraSQMLcpDLs+N1lVdXQ+zwytSVNZBnWKhDu5ggtkjjQ67Egt0Vfwy91KxXVPc+8Ex4onO/RykKoPuaF7VUSHuXul/S7ZbWl8Ysk9DM/ej7u4H5Vyod8I70AH6bv6tTn921nyi9m5P5lvkVlEMkv/fFQpp9pVTAwfXtjqf2HM4h7iFYN+iZc0DKnLor2Y8t4bStrXKRUvonuJ5qX+MRB4DjBgttEc/AnTdxTIMwc3FsMqpxN5UAXZVp1kfIBMhzYZYOIJwQumhEaTBUxlzZTyQtton1e0gwvnVf361Wr1qyVlArDjwS6WORaRkcPkFw5UnBRmhTIH0QNUKmQ+zMYONDrFlXgyIUI8aiUg5TgAUbPfzILXf8sxeqo1MYWTOqF+zS4kpOTlHT5uTcAinijJAc9+0lht3c6XAB1cgO0NS5eP3mrt6y1kJGbs15z6LpkqEmS+824aw7JAdcgyuKKx2QwFQr6o80qOEo2TGwg4UMoPUG+NM1qFgVOV+jsAW38h0THHrY1iLyFuFpEGLW565vtEPzk9rNdsPzqRnrcObTAbHICjGSJSK57JKg16oTL7h9aQXMeduPJeziQ="
    matrix:
        - SMVERSION=1.8 # Stable
        - SMVERSION=1.9 # Unstable

# Allow the experimental branch to fail
matrix:
  fast_finish: true
  allow_failures:
    - env: SMVERSION=1.9

install:
    - wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
    - tar -xzf $(cat sourcemod-latest-linux)
    - COMPILE_SOURCEMOD_FOLDER="$TRAVIS_BUILD_DIR/addons/sourcemod"
    - COMPILE_SCRIPTING_FOLDER="$TRAVIS_BUILD_DIR/addons/sourcemod/scripting"
    - wget https://bitbucket.org/GoD_Tony/updater/raw/default/include/updater.inc -O $COMPILE_SCRIPTING_FOLDER/include/updater.inc
    - COMMIT_NUMBER=$(git rev-list --count HEAD)
    - if [[ -z $TRAVIS_TAG ]]; then if git describe --tags; then TAG=$(git describe --tags); else TAG="_untagged_"; fi; else TAG="$TRAVIS_TAG"; fi
    - VERSION="$TAG.$COMMIT_NUMBER"
    
before_script:
    - cp -r "$TRAVIS_BUILD_DIR/scripting" "$COMPILE_SOURCEMOD_FOLDER"
    - chmod +x "$COMPILE_SCRIPTING_FOLDER/spcomp"
    - mkdir "$TRAVIS_BUILD_DIR/plugins"
    - FILE=$PROJECT_SHORTNAME-n$COMMIT_NUMBER.zip
# And compile!

script: 
    - $COMPILE_SCRIPTING_FOLDER/spcomp $COMPILE_SCRIPTING_FOLDER/example.sp -o$TRAVIS_BUILD_DIR/plugins/example.smx

before_deploy: 
    - cd $TRAVIS_BUILD_DIR
    - PACKAGE_DIRS[0]="./plugins/"
    - PACKAGE_DIRS[1]="./scripting/" 
    - zip -r $FILE ${PACKAGE_DIRS[*]}
    
    - PACKAGE_PATH="$TRAVIS_BUILD_DIR/.package_updater"
    - UPDATER_SCRIPTS_PATH="$TRAVIS_BUILD_DIR/.buildtools/tony_updater"
    
    - rm -rf "$PACKAGE_PATH/"
    - mkdir "$PACKAGE_PATH/"
    - cp -r ${PACKAGE_DIRS[*]} "$PACKAGE_PATH/"
    - python3.5 "$UPDATER_SCRIPTS_PATH/updater_script_gen.py" --sm_path "$PACKAGE_PATH" --version "$VERSION" --notes "Version $VERSION is out!" "Go to $URL to see the changes" --output "$PACKAGE_PATH/updater.txt"
    - chmod +x "$UPDATER_SCRIPTS_PATH/deploy.sh"

deploy:
    - provider: releases
      api_key:
          secure: B9lka6u0jkPxHGPqGUzLESQvlFSi5FTj2KVx2w+gtILzUFeXwRUwvFr6UveU4PAcFPzvUOfchItXGW682Ljh1HCo0bUcBLgSdvBJuZPeqTFHpf4y2hjb8E+mQwaZ0aEgWfqfq9w9ZtH+03Q+8kKQpUBARDOGrn5unuKH3IXOVqfKt5PkBaF/9Eb9fP88u0vDdkJ00S0/M3Nm23DoN5XzDovN3amPP+WfsdlrxOx5zKfSZdLCv+Qxi1cRr6tyljMrtWpPh+vepD4moLYRbQuKgQkr7iweBornxe0Y/xyWcQGoLxz3jnyDzlLisGE1DdU5kItaAITRGAYHw7UE0Bjg7kBi8ISlJqF7lgbrNKTRUUJMvk/KK4uP0mP1PaUyhdU69PJQALTM/XRsqd7+/HWeqSgKriI5FRoncv4iKrAo/mzsi/5hTc/FW3Q0P1zNZYfiSLCdfAfQ/0EaoIkQzDNhBc1c42U6BN6SG//qoLCRLXqdbPzbd703KiYeAGYKWMv79N+kYK3Y3gHTBduNbANB3BonhCdkqC+j1cZ0Gwd6P7lL0+kEhSIdo3cDx08RZ0vCVPCfi95bGJNc2VvOuyRtQVcffAxzaDU9W/TLT3kQ5nd1RgrXhhPgw6DvFuJIbfgTiUz/s9YsX4ChJFN5Mog9VZukWG9zRTFn7MXg9Rhqny4=
      file: $FILE
      skip_cleanup: false
      on:
          branch: master
          condition: $SMVERSION = 1.8
          repo: servadestroya/sample_plugin_autoupdated
          tags: true
        
    - provider: script
      script: '"$UPDATER_SCRIPTS_PATH/deploy.sh" "$PROJECT_SHORTNAME" "$VERSION" "$UPDATER_REPO" "$UPDATER_USER" "$UPDATER_REPO_OAUTH"'
      skip_cleanup: false
      on:
          branch: updater
          condition: $SMVERSION = 1.8
          tags: false

# Notifications
notifications:
    email: false
