# Use the new container-based infrastructure
sudo: false

# Install some apt packages needed for spcomp
addons:
    apt:
        sources: 
            - deadsnakes
        packages:
            - lib32stdc++6
            # We need at least python3.4 to run our custom deployment scripts
            - python3.5

# Set the build environment
env:
    - SMVERSION=1.8 # Stable
    - SMVERSION=1.9 # Unstable

# Allow the experimental branch to fail
matrix:
  fast_finish: true
  allow_failures:
    - env: SMVERSION=1.9

install:
    - wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
    - tar -xzf $(cat sourcemod-latest-linux)
    - COMPILE_SOURCEMOD_FOLDER="$TRAVIS_BUILD_DIR/addons/sourcemod"
    - COMPILE_SCRIPTING_FOLDER="$TRAVIS_BUILD_DIR/addons/sourcemod/scripting"
    - wget https://bitbucket.org/GoD_Tony/updater/raw/default/include/updater.inc -O $COMPILE_SCRIPTING_FOLDER/include/updater.inc
    - COMMIT_NUMBER=$(git rev-list --count HEAD)
    
before_script:
    - cp -r "$TRAVIS_BUILD_DIR/scripting" "$COMPILE_SOURCEMOD_FOLDER"
    - chmod +x "$COMPILE_SCRIPTING_FOLDER/spcomp"
    - mkdir "$TRAVIS_BUILD_DIR/plugins"
    - FILE=example-n$COMMIT_NUMBER.zip
# And compile!

script: 
    - $COMPILE_SCRIPTING_FOLDER/spcomp $COMPILE_SCRIPTING_FOLDER/example.sp -o$TRAVIS_BUILD_DIR/plugins/example.smx

before_deploy: 
    - PACKAGE_DIRS[0]="./plugins/"
    - PACKAGE_DIRS[1]="./scripting/"
    - zip -r $FILE ${PACKAGE_DIRS[*]}

deploy:
    provider: releases
    api_key:
        secure: B9lka6u0jkPxHGPqGUzLESQvlFSi5FTj2KVx2w+gtILzUFeXwRUwvFr6UveU4PAcFPzvUOfchItXGW682Ljh1HCo0bUcBLgSdvBJuZPeqTFHpf4y2hjb8E+mQwaZ0aEgWfqfq9w9ZtH+03Q+8kKQpUBARDOGrn5unuKH3IXOVqfKt5PkBaF/9Eb9fP88u0vDdkJ00S0/M3Nm23DoN5XzDovN3amPP+WfsdlrxOx5zKfSZdLCv+Qxi1cRr6tyljMrtWpPh+vepD4moLYRbQuKgQkr7iweBornxe0Y/xyWcQGoLxz3jnyDzlLisGE1DdU5kItaAITRGAYHw7UE0Bjg7kBi8ISlJqF7lgbrNKTRUUJMvk/KK4uP0mP1PaUyhdU69PJQALTM/XRsqd7+/HWeqSgKriI5FRoncv4iKrAo/mzsi/5hTc/FW3Q0P1zNZYfiSLCdfAfQ/0EaoIkQzDNhBc1c42U6BN6SG//qoLCRLXqdbPzbd703KiYeAGYKWMv79N+kYK3Y3gHTBduNbANB3BonhCdkqC+j1cZ0Gwd6P7lL0+kEhSIdo3cDx08RZ0vCVPCfi95bGJNc2VvOuyRtQVcffAxzaDU9W/TLT3kQ5nd1RgrXhhPgw6DvFuJIbfgTiUz/s9YsX4ChJFN5Mog9VZukWG9zRTFn7MXg9Rhqny4=
    file: $FILE
    skip_cleanup: true
    on:
        branch: master
        condition: $SMVERSION = 1.8
        repo: servadestroya/sample_plugin_autoupdated
        tags: true

# Notifications
notifications:
    email: false
